version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: node_backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    command: yarn dev

volumes:
  mongo_data:
